stages:
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        echo "Hi"
        import os
        command = 'kubectl get pods'
        p = os.system('sudo -S %s' % (command))
- name: test2
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "Hi2"
timeout: 60
notification: {}
