stages:
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        apt-get install sshpass
        #sshpass -p password ssh -tt -o StrictHostKeyChecking=no root@10.0.8.64 arr=kubectl --kubeconfig=config get pods -n=p-jnm8q-pipeline | grep hello-world | echo $arr | cut -d' ' -f3
        sshpass -f ./key.pem ssh -tt -o StrictHostKeyChecking=no centos@192.168.100.178 ./run.sh
        #arr=`kubectl --kubeconfig=config get pods -n=p-jnm8q-pipeline | grep hello-world`
        #echo $arr | awk {'print $3'}
    when:
      event:
        include:
        - pull_request
        - push
        - tag
  when:
    event: {}
- name: test2
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "Hi2"
    when:
      event:
        include:
        - pull_request
        - push
        - tag
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      event: {}
- name: Checking pod status
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        #sshpass -p password ssh -tt -o StrictHostKeyChecking=no root@10.0.8.64 arr=kubectl --kubeconfig=config get pods -n=p-jnm8q-pipeline | grep hello-world | echo $arr | cut -d' ' -f3
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no root@10.0.8.64 ./run.sh p-jnm8q-pipeline hello-world
    when:
      event: {}
- name: Test Stage
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "HI"
timeout: 60
notification: {}
