stages:
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        echo "Hi"
        exit 1
- name: test2
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "Hi2"
timeout: 60
notification: {}
